language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_script:
  - cd Lotto_springboot_dev/
  - chmod +x ./gradlew
# Travis CI 서버의 Home
# gradle 을 통해 의존성을 받게 되면 이를 해단 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r lotto-springboot2-webservice *
  - mkdir -p deploy
  - mv lotto-springboot2-webservice.zip deploy/lotto-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: lotto-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: lotto-springboot-build
    key: lotto-springboot2-webservice.zip
    bundle_type: zip
    application: lotto-springboot2-webservice
    deployment_group: lotto-springboot2-webservice
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dlckd125@nate.com