spring:
  profiles:
    active: local

server:
  servlet:
    context-path: /api

logging:
  level:
    com.lotto: debug
jwt:
  secret: "sdaspdjaskdjsaknfoasofnqwownfqfjoqwfnouwqnvownquvnqiwunvqviwqnowvniqwvuqwnivnqiwnvuiqwnviqwnvqwuinvuqiwnvwqiuvwnwuqivquiwdxn"
  expiration: 3600000
---
spring:
  profiles: local
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  sql:
    init:
      enabled: true
#      mode: always


---
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://172.30.1.69:3306/change2
    username: root
    password: humuson123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: NEVER
  jpa:
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
