// SignUp2
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "dlckd125@nate.com",
  "nickname": "dlckd",
  "password": "1234"
}

###

// SignUp
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "token-test2@test.com",
  "nickname": "token-te",
  "password": "hashed_password_1234"
}

###

// Request
POST http://172.30.1.99:8080/auth/login
Content-Type: application/json

{
    "email": "token-test2@test.com",
    "password": "hashed_password_1234"
}

###

// Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "dlckd125@nate.com",
  "password": "1234"
}

###

// Request
GET http://localhost:8080/member/me
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY5MjM0MzkzNX0.Xj31PvQvcPwpMo4ufbh1kregfP4486YMeBLIr6r0_PM1scQCrytkEXEHB0EeimYPGKanso7iF2r7XgrBzP_4ng


###
GET https://dhlottery.co.kr/gameResult.do?method=byWin


###
POST https://dhlottery.co.kr/gameResult.do?method=byWin
Content-Type: text/html;charset=EUC-KR

{
  "drwNo": "1",
  "dwrNoList": "1080"
}

###

GET http://localhost:8080/game/round/3